name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # lets you run manually from the Actions tab

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Shafin1196
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Commit and push
        run: |
          mkdir -p assets
          mv dist/* assets/
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/
          git commit -m "Update snake animation" || echo "No changes"
          git push
