name: Generate Snake

on:
  schedule:               # run daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:      # allow manual runs

# needed so the action can push to your repo
permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Generate the SVGs (light and dark)
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Shafin1196
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # Push the generated files to the "output" branch (root of that branch)
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
