name: Generate Snake

on:
  schedule: # run automatically every 24 hours
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Shafin1196
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake animation
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/github-contribution-grid-snake.svg"
